steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/my-docker-repo/myimage', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/my-docker-repo/myimage']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  timeout: 240s
  args: ['run', 'deploy', 'pricecompare', '--image', 'gcr.io/${PROJECT_ID}/my-docker-repo/myimage', '--region', 'us-central1']
images:
- gcr.io/${PROJECT_ID}/my-docker-repo/myimage
options:
  logging: CLOUD_LOGGING_ONLY
